config/routes.rb
  Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  root 'home#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users, only: [:new, :edit]

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    create! do |auth|
      auth.provider = auth_hash["provider"]
      auth.uid = auth_hash["uid"]
      auth.token = auth_hash["credentials"]["token"]
    end
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  include Clearance::User
 
  has_many :authentications, :dependent => :destroy
  
  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.first_name = auth_hash["info"]["first_name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.authentications<<(authentication)
    end
  end

  
  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end
  
  
  def password_optional?
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentication_controller.rb
class Authentication < ActiveRecord::Base

  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    create! do |auth|
      auth.provider = auth_hash["provider"]
      auth.uid = auth_hash["uid"]
      auth.token = auth_hash["credentials"]["token"]
    end
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

  def create_from_omniauth
    auth_hash = request.env["omniauth.auth"]

    authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
    if authentication.user
      user = authentication.user 
      authentication.update_token(auth_hash)
      @next = root_url
      @notice = "Signed in!"
    else
      user = User.create_with_auth_and_hash(authentication,auth_hash)
      @next = edit_user_path(user)   
      @notice = "User created - confirm or edit details..."
    end
    sign_in(user)
    redirect_to @next, :notice => @notice
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Contact Us</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Country</a></li>
        <li><a href="#">Entertainment</a></li> 
        <li><a href="#">PairBnB Suggestions</a></li> 
      </ul>
    </div>
  </div>
</nav>



<div>
<h1><font color="red">Pair BnB</font><h1>
<h3>Home#index</h3>
<p>Find me in app/views/home/index.html.erb</p>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-6 col-xs-12"><img class="img-responsive" src="http://www.conferencesthatwork.com/wp-content/uploads/2014/01/airbnb-growth-tweet.jpg" alt="Via PairBnB"></div>
  </div>
  <div class="row">
    <div class="col-md-4">Left test-column</div>
    <div class="col-md-4">Center test-column</div>
    <div class="col-md-3">Right test-column</div>
   
     <div>
	

			 <br>
			 <h2>List Your Space</h2>

			<p>We encourage you to share all kinds of spaces on Airbnb! Whether you’re offering a seaside villa or an air mattress in the corner of your living room, it’s free to list your space. When you’re ready to start welcoming guests, you can publish your listing for the world to see.</p>

			<h2>Learn More</h2>
			<h3>Description and amenities</h3>

			<p>Guests often search for spaces that meet specific needs, so accurately describing your listing and the amenities you offer will help attract the kinds of guests that are best for you. When telling the story of your space, answer important questions like whether or not you have Wifi, and include helpful details about the character, activities, and transportation options in the surrounding area.</p>
			<br>
			<h3>Photos</h3>

			<p>Photographs help guests picture themselves in your space. Go ahead and upload up to 24 images, and make sure your photos are well lit, in focus, and representative of the actual space your guests have access to.</p>

			<p>We love lush imagery, so we offer free professional photography to active hosts in most areas. Apply online and we'll send a professional photographer to capture your listing in its best light.</p>

			<h3>Pricing and availability</h3>

			<p>You know your space and your schedule best, so we let you decide the price and we ask you to update your calendar to reflect when it’s available to rent. We also allow you to set custom prices for individual nights and weekends, special events, and monthly stays. We display your listing at the price you set and when you indicate that your space is unavailable, we make sure not to show it in search results.</p>
  	</div>
  <div class="row">
  <br>
  <br>
    <button type="button" class="btn btn-danger">Become a Host</button>
    <br>
  </div>
</div>

<br>

<div class="jumbotron">
<h3><center> Hosted over 1,000,000 stays all over the world</center></h3>
</div>

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pairbnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <% if signed_in? %>
      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign in', sign_in_path %>
    <% end %>

    <br>

    <li><%= link_to 'Facebook', '/auth/facebook' %></li>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>


<%= yield %>

</body>
</html>